// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBboCD_sEjIPhkxWbE5Q5OHo8jDSR9zUIQ',
    appId: '1:302031379998:web:df8812cf633b87f8d7180f',
    messagingSenderId: '302031379998',
    projectId: 'chattiely',
    authDomain: 'chattiely.firebaseapp.com',
    storageBucket: 'chattiely.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj-hDnInpC8qzE1VlnHYHCOsRMqO3XWcY',
    appId: '1:302031379998:android:c7016ad414c300e0d7180f',
    messagingSenderId: '302031379998',
    projectId: 'chattiely',
    storageBucket: 'chattiely.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeiL5A6Kx5cq4ZpOqEE1hSRB-x86BWhEA',
    appId: '1:302031379998:ios:56bc30a00e34d47ed7180f',
    messagingSenderId: '302031379998',
    projectId: 'chattiely',
    storageBucket: 'chattiely.appspot.com',
    iosClientId: '302031379998-240os23vlf68u4i85uimsu347lnn2flf.apps.googleusercontent.com',
    iosBundleId: 'com.example.w10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeiL5A6Kx5cq4ZpOqEE1hSRB-x86BWhEA',
    appId: '1:302031379998:ios:56bc30a00e34d47ed7180f',
    messagingSenderId: '302031379998',
    projectId: 'chattiely',
    storageBucket: 'chattiely.appspot.com',
    iosClientId: '302031379998-240os23vlf68u4i85uimsu347lnn2flf.apps.googleusercontent.com',
    iosBundleId: 'com.example.w10',
  );
}
